version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
  db:
    image: postgres:latest
    #restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - db_network

  # backend:
  #   build: ./backend
  #   ports:
  #     - "7777:7777"
  #   networks:
  #     - db_network

  pgadmin:
    image: dpage/pgadmin4:latest
    #restart: always
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: zaq1@WSX
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
